spring.application.name=Biblioteca
#puerto por defecto
server.port=8082
#Base Datos
#JPA

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
#spring.thymeleaf.check-template-location=false